version: '3.8'

services:
  mbta:
    image: mbta
    volumes:
      - ./db.sqlite3:/opt/app/db.sqlite3
    ports:
      - 8000:8000
    environment:
#      DJANGO_DEBUG: True
      DJANGO_ALLOWED_HOSTS: 'localhost,127.0.0.1'
#      DJANGO_SQL_ENGINE: 'django.db.backends.postgresql'
#      DJANGO_SQL_DATABASE: 'mbta'
#      DJANGO_SQL_USER: 'postgres'
#      DJANGO_SQL_PASSWORD: 'postgres'
#      DJANGO_SQL_HOST: 'postgres'
#      DJANGO_SQL_PORT: 5432
      # URL schema: postgres://user:password@host:port/dbname
      DJANGO_DATABASE_URL: 'postgres://postgres:postgres@postgres:5432/mbta'


  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mbta
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"