# Generated by Django 5.0 on 2023-12-27 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'line',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='django_intro_app.line')),
            ],
            options={
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='django_intro_app.line')),
            ],
            options={
                'db_table': 'train',
            },
        ),
    ]
