# Generated by Django 5.0 on 2023-12-29 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_intro_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='direction',
            field=models.IntegerField(choices=[(0, 'Inbound'), (1, 'Outbound')], default=0),
        ),
        migrations.AddField(
            model_name='station',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='django_intro_app.line'),
        ),
    ]
