# Generated by Django 5.0 on 2024-01-10 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('django_intro_app', '0003_alter_station_line'), ('django_intro_app', '0004_remove_station_order_branchstation_branch_stations'), ('django_intro_app', '0005_alter_branchstation_table')]

    dependencies = [
        ('django_intro_app', '0002_branch_direction_station_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='django_intro_app.line'),
        ),
        migrations.RemoveField(
            model_name='station',
            name='order',
        ),
        migrations.CreateModel(
            name='BranchStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='django_intro_app.branch')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='django_intro_app.station')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='stations',
            field=models.ManyToManyField(through='django_intro_app.BranchStation', to='django_intro_app.station'),
        ),
        migrations.AlterModelTable(
            name='branchstation',
            table='branch_station',
        ),
    ]
