# Generated by Django 5.0 on 2024-01-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_intro_app', '0003_alter_station_line_squashed_0005_alter_branchstation_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchstation',
            options={'ordering': [models.OrderBy(models.F('order'))]},
        ),
        migrations.AlterField(
            model_name='branch',
            name='stations',
            field=models.ManyToManyField(related_name='branches', through='django_intro_app.BranchStation', to='django_intro_app.station'),
        ),
        migrations.AddIndex(
            model_name='line',
            index=models.Index(fields=['color'], name='line_color_deb037_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['name'], name='station_name_9ef58b_idx'),
        ),
    ]
