# Generated by Django 5.0 on 2024-01-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_intro_app', '0007_branchstation_branch_order_and_more_squashed_0008_alter_branchstation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchstation',
            name='id',
        ),
        migrations.AddField(
            model_name='branchstation',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
