# Generated by Django 5.0 on 2024-01-15 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_intro_app', '0014_remove_train_line_train_branch_and_more_squashed_0015_alter_branchstation_id_alter_train_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingDevice',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('api_key', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'tracking_device',
            },
        ),
        migrations.CreateModel(
            name='TrainRegistration',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tracking_device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_intro_app.trackingdevice')),
                ('train', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_intro_app.train')),
            ],
            options={
                'db_table': 'train_registration',
            },
        ),
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(max_length=8, unique=True, db_index=True),
        ),
    ]
